name: Auto Update Abema Playlist

on:
  schedule:
    - cron: '0 0 * * *' # Berjalan otomatis setiap hari jam 00:00 UTC
  workflow_dispatch:     # Tombol manual di tab Actions

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # Menggunakan v4 yang sudah mendukung Node terbaru
        uses: actions/checkout@v4

      - name: Download and Edit File
        run: |
          # \x3d adalah '=' dan \x22 adalah '"'
          # Perintah ini akan menghapus '==' yang berada tepat sebelum '"'
          curl -L -s "https://raw.githubusercontent.com/dbghelp/Abema-TV/refs/heads/main/abema.m3u8" | sed 's/\x3d\x3d\x22/\x22/g' > abema_fixed.m3u8

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add abema_fixed.m3u8
          # Commit hanya jika ada perubahan untuk menghindari error
          git commit -m "Update playlist: Fixed quotes and equals signs" || exit 0
          git push
